# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_date', 'author']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('text',)]),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('title', 'text')]),
        ),
    ]
